version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - frontend
      - go-api
      - ml-service
    restart: unless-stopped

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: voicebook_user
      POSTGRES_PASSWORD: voicebook_password
      POSTGRES_DB: voicebook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voicebook_user -d voicebook_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_go_api=https://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - go-api
    restart: unless-stopped

  go-api:
    build:
      context: ./backend/go_api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://voicebook_user:voicebook_password@postgres:5432/voicebook_db?sslmode=disable
      - ML_SERVICE_URL=http://ml-service:8000
      - LISTEN_ADDR=:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/go_api:/app
    ports:
      - "8080:8080"
    command: go run cmd/api/main.go
    restart: unless-stopped

  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    environment:
      - SERVICE_ACCOUNT_ID=${SERVICE_ACCOUNT_ID}
      - KEY_ID=${KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - FOLDER_ID=${FOLDER_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_KEY_ID=${SECRET_KEY_ID}
    volumes:
      - ./ml:/app
    ports:
      - "8000:8000"
    command: python ml_api.py
    restart: unless-stopped

volumes:
  postgres_data: