services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
#    ports:
#      - "443:443"
#      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      go_api:
        condition: service_healthy
      ml-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - localnet
      - shared

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U voicebook_user -d voicebook_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - localnet



  go_api:
    build:
      context: ./backend/go_api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - ML_SERVICE_URL=http://ml-service:8000
      - LISTEN_ADDR=:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/go_api:/app
    command: ./go_api   # âœ… run the built binary instead of 'go run'
    restart: unless-stopped
    networks:
      - localnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    environment:
      - SERVICE_ACCOUNT_ID=${SERVICE_ACCOUNT_ID}
      - KEY_ID=${KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - FOLDER_ID=${FOLDER_ID}
      - BUCKET_NAME=${BUCKET_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_KEY_ID=${SECRET_KEY_ID}
    volumes:
      - ./ml:/app
    networks:
      - localnet
    command: python ml_api.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  shared:
    external: true
    name: my-shared-network
  localnet: